# @file apps/panther/Cargo.toml
# @description Declares the Panther application binary.
# @created Diego Martín Lafuente <meerita@icloud.com>

[package]
name = "panther"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
panther-browser = { path = "../../products/panther/browser" }
panther-window = { path = "../../products/panther/window" }
