# @file engines/purr/engine/Cargo.toml
# @description Declares the Purr web engine core package.
# @created Diego Martín Lafuente <meerita@icloud.com>

[package]
name = "purr-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
capability-system.workspace = true
memory.workspace = true
purr-graphics.workspace = true
purr-text.workspace = true
thiserror.workspace = true
